DROP TABLE IF EXISTS stocks;

CREATE TABLE stocks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    [Date] TIMESTAMP NOT NULL,
    ticker TEXT NOT NULL,
    [Close] FLOAT NOT NULL,
	High FLOAT NOT NULL,
	Low FLOAT NOT NULL,
	[Open] FLOAT NOT NULL,
	Volume FLOAT NOT NULL
);